# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
s3: &s3
  ACCESS_KEY_ID: <%= ENV["ACCESS_KEY_ID"] %>
  SECRET_ACCESS_KEY: <%= ENV["SECRET_ACCESS_KEY"] %>
  BUCKET: <%= ENV["BUCKET"] %>
  S3_HOST_NAME: <%= ENV["S3_HOST_NAME"] %>

s3: &s3
  BUCKET: <%= ENV["S3_BUCKET_NAME"] %>
  AWS_REGION: <%= ENV["S3_REGION"] %>
  ACCESS_KEY_ID: <%= ENV["AWS_ID"] %>
  SECRET_ACCESS_KEY: <%= ENV["AWS_KEY"] %>

bucket: https://console.aws.amazon.com/s3/home?region=us-east-1#&bucket=photo-vikings&prefix=


development:
  secret_key_base: c9015099ab9235919e195d8f0fe14e05f5ecdd98f45d2bcbe2fcc400f682a2adb7348e1b63a66410c3ac6070b8516d3a31ff1c8aef6264ccbd4c082f1b0ef08f
  <<: *s3

test:
  secret_key_base: dbca5af224ab6ca6284f23ada0a15bd74ec4279899cee56f874d303384bfba723efc9a2733224b0ea9dc47da1b7385fc7525bf781ca0ebf16ea604964dbd9b69
  <<: *s3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *s3
